{% set name = "hiclass" %}
{% set version = "5.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef12425eafe41c6498e6c55a891157b44c2ae575dc30a001025fa4fac96bc2d3

build:
  noarch: python
  number: 0
  entry_points:
    - hiclass = hiclass.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - networkx
    - numpy
    - scikit-learn >=1.5
    - ray-core
    - scipy

test:
  imports:
    - hiclass
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/scikit-learn-contrib/hiclass
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Hierarchical Classification Library
  description: |
    HiClass is a library for hierarchical classification which
    is inspired in scikit-learn's usability and is optimized
    for speed. It is pure python code compatible with
    Python 3.8+ and requires networkx, numpy and scikit-learn.
  doc_url: https://hiclass.readthedocs.io/
  dev_url: https://github.com/scikit-learn-contrib/hiclass

extra:
  recipe-maintainers:
    - mirand863
