{% set name = "hiclass" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbfbda6fb635b8f786b44516d2ad601faa8308fea23fe2cdc81025c10e218e05

build:
  noarch: python
  number: 0
  entry_points:
    - hiclass = hiclass.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<3.9
    - pip
  run:
    - python >=3.8,<3.9
    - networkx
    - numpy
    - scikit-learn
    - ray-all=1.9.2

test:
  imports:
    - hiclass
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/dacs-hpi/hiclass
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Hierarchical Classification Library
  description: |
    HiClass is a library for hierarchical classification which
    is inspired in scikit-learn's usability and is optimized
    for speed. It is pure python code compatible with
    Python 3.8+ and requires networkx, numpy and scikit-learn.
  doc_url: https://hiclass.readthedocs.io/
  dev_url: https://gitlab.com/dacs-hpi/hiclass

extra:
  recipe-maintainers:
    - mirand863
